# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  dockerhub-hardened-images:
    type: docker-registry
    url: https://dhi.io
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: weekly
      day: sunday
      
  - package-ecosystem: "docker"
    directory: "/"
    registries:
        - dockerhub-hardened-images
    schedule:
      interval: weekly
      day: sunday

  - package-ecosystem: "gradle"
    # Look for build.gradle files from the `root` directory
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    groups:
      ktor-swagger:
        patterns:
          - "io.github.smiley4:ktor*"
      patch-dependencies:
        patterns:
          - "*"
        update-types:
            - "patch"
